title:        "The Grid Report"
description:  "A publication to know how to ask questions."
baseurl:      ""
keywords:     "Design, Frontend, UX, Art-Directed, Essays"
url:          "https://thegrid.report"
ga:           "UA-58152304-7"
author:
  name: "Rogues"
  twitter: "ro9ues"

# Build settings
markdown: kramdown
theme: minima
