title:        "The Grid Report"
description:  "A publication to know how to ask questions."
baseurl:      ""
keywords:     "Design, Frontend, UX, Art-Directed, Essays"
# url:          "https://thegrid.report"
url:          "http://127.0.0.1:4000"
author:
  name: "Rogues"
  twitter: "imrogues"

# Build settings
markdown: kramdown
theme: minima
